### PR TITLE
Rename observation to record (as per glossary)

### PR DESCRIPTION
**Pull request by aragilar**
This is the second of the rename PRs, for observation to record.

### CODE REVIEW

**Comment by Denubis** [comment]
I'm happy for the base collection of (things, probably attribute-value-pairs...) to be renamed to Record. I approve this PR :)

**Comment by Denubis** [comment]
@aragilar back to you. I thought I merged the two, but since it's failing I... obviously didn't do it well.

**Comment by aragilar** [comment]
It might be worth setting up https://bors.tech/ for this repo. I use it for my projects, and it lets you queue up merges and it sorts them out if it can, and if it fails, then I rebase the PRs onto the current prod branch, and tell bors to redo the tests.

**Comment by Denubis** [comment]
Can do.

**Pull request merged**
