### PR TITLE
Improve Auto-incrementers

### PR DESCRIPTION
**Pull request by stevecassidy**
# Fix: Improve Auto-incrementers

## JIRA Ticket

None

## Description

Auto increment fields are used to generate human readable IDs for records.  There 
was a bug that caused them to not work if the initial value of the field was 
set to "" as it was in the designer. 

These fields require that a range of numbers is set for the device before records can
be properly created.  The past behaviour was to notice when they weren't set up but
not really help the user set them.

## Proposed Changes

- Deals with the case when the initial value is ""
- Turn the range setting form into a popup dialog
- trigger the popup if a user tries to create a record without the ranges being set

## How to Test

Open a notebook with an auto increment field configured, eg. [Campus Survey](https://github.com/FAIMS/FAIMS3-Notebook-Campus-Survey-Demo).  Try to create
a record after activating the notebook, you should see a popup to allow you to set
the ranges.

Same popup is accessible via the Settings tab on the notebook.

## Checklist

- [x] I have confirmed all commits have been signed.
- [x] I have added JSDoc style comments to any new functions or classes.
- [x] Relevant documentation such as READMEs, guides, and class comments are updated.

### CODE REVIEW

**Comment by luke-mcfarlane-rocketlab** [comment]
I get the following error:
Screenshot 2024-11-28 at 3 57 43 PM

As a side note, could we create an auto-incrementer that doesn't require any user input?

**Comment by stevecassidy** [comment]
Thanks for picking that up. I'll look at that.   The whole idea of incrementers is that the user gets to set the range, if not, then you get clashes between different users and the number is meaningless.

**Comment by stevecassidy** [comment]
Following up on that error message. It's due to some old notebooks having initialValue=null for the field which is invalid according to the validation schema.  I can't get around that in code, we need to update those notebooks. I've added a migration in the notebook editor to automatically fix this for any notebook that is edited.  

Also rewrote the edit form to be bit nicer and use useQuery :-)

**Review by PeterBaker0 — APPROVED** [review]
code lgtm - see use of react query with cache invalidation - makes sense in this case I think

**Pull request merged**
