### PR TITLE
minor enhancements to inProgress component

### PR DESCRIPTION
**Pull request by ranisa-gupta16**
## JIRA Ticket

Parent Jira Issue: browse
Subtask: https://jira.csiro.au/browse/BSS-299

## Description

Minor enhancement to inprogress component to make it more clearly visible to the developer.

## Proposed Changes

- Typography updated
- More clearly visible

## How to Test

- When in local dev mode, you should be able to see "feature in progress" disclaimer with icon at the bottom of the content of the page.

## Checklist

- [Y] I have confirmed all commits have been signed.
- [Y] I have added JSDoc style comments to any new functions or classes.
- [Y] Relevant documentation such as READMEs, guides, and class comments are updated.

### CODE REVIEW

**Comment by PeterBaker0** [comment]
@luke-mcfarlane-rocketlab would you mind taking a look at this?

**Review by luke-mcfarlane-rocketlab — APPROVED** [review]
LGTM - the component looks really nice, we should generalise the component and reuse next time we need a card implemented

**Comment by stevecassidy** [comment]
Looks nice but I don't think we even use this indicator anywhere in the app to indicate a feature in progress - it only seems to be used in this spot. Do we really need it? (I don't know the history, it might have been used at some point when we had many features in development).

**Comment by ranisa-gupta16** [comment]
> Looks nice but I don't think we even use this indicator anywhere in the app to indicate a feature in progress - it only seems to be used in this spot. Do we really need it? (I don't know the history, it might have been used at some point when we had many features in development).

Yeha not sure why it's needed but as I see it in local dev, just made an improvement. Rest I'll leave it y'll to decide whether we need this component.

**Pull request merged**
