### PR TITLE
Update capacitor to v3

### PR DESCRIPTION
**Pull request by aragilar**

### CODE REVIEW

**Comment by riniangreani** [comment]
@aragilar What are the criterias I'm reviewing against?

**Comment by riniangreani** [comment]
Unfortunately the "sign in with data central" button doesn't work on Android. It doesn't do anything.
I can't test iOS because it's not on Test Flight. @aragilar

**Comment by riniangreani** [comment]
Signing in works well with Chrome.

**Comment by Denubis** [comment]
@aragilar I'm going to recommend rejecting this PR in any case. I don't see any edits you've made to unit tests. How long has it been since you touched those files? I'd imagine that some of our tests need to change for a major version update? (And if they don't... ... what are we testing?)

**Comment by Denubis** [comment]
Also, looking at our tests, they... haven't been touched (besides a license upgrade in over a year?) Did we go two dev cycles without you AAO folk adding *any* unit tests?

**Comment by aragilar** [comment]
Uh, I'd be surprised if the unit tests needed changing for capacitor, the main change in the code is modified import paths (capacitor has been great in terms of backwards compatibility). I'd expect this would break browserstack, but as that's not doing anything currently. Capacitor hasn't changed its APIs.

**Comment by aragilar** [comment]
I last touched the merging tests in January? Which files are you looking at?

**Comment by Denubis** [comment]
More that there haven't been any tests touched since Jan 202*1* as far as I can tell? I'm wondering if this is wise?

**Comment by riniangreani** [comment]
I managed to test on IOS (thanks to Brian). Triggered the build to deploy branch build on TestFlight: https://github.com/FAIMS/FAIMS3/runs/5622267058?check_suite_focus=true. 
It's still opening Safari and not in-app browser, therefore still stuck on "Sending Auth".

**Comment by aragilar** [comment]
@riniangreani https://github.com/FAIMS/FAIMS3/actions/runs/1943041747 seems to work for me, can you try it and see?

**Comment by riniangreani** [comment]
@aragilar yes that one works for Android. Is there one for IOS to test too?

**Comment by aragilar** [comment]
@riniangreani I need to get the physical hardware set up again, but if android works, then if the iOS app starts (so we've got the app web view working), which I think you found, I think this is ready to merge, and we can fix the iOS login issue separately (as that is not handled by capacitor, rather cordova).

**Comment by aragilar** [comment]
Rebased to remove merge conflict.

**Comment by riniangreani** [comment]
Testing this. On Chrome, I'm getting the undefined draft id issue documented here: https://faimsproject.atlassian.net/browse/FAIMS3-374. 
What am I doing wrong?

**Comment by aragilar** [comment]
@riniangreani This won't fix that issue (so anything affecting the mui5 upgrade will also affect this).

**Comment by riniangreani** [comment]
OK. mui5 upgrade shouldn't have been merged with known issues and it wasn't fully tested yet.

**Comment by riniangreani** [comment]
By the way, iPad still opens safari upon signing in with the latest version of this branch. Will test android now. @aragilar

**Comment by riniangreani** [comment]
On the positive note, signing in and take photos work fine with android @aragilar

**Pull request merged**
