### PR TITLE
Staging refactor

### PR DESCRIPTION
**Pull request by aidanfar0**
Moves logic for staging area into a new object and file, out of the ObservationForm

### CODE REVIEW

**Comment by aragilar** [comment]
@aidanfar0 Can you rebase to resolve the conflicts? Once that's done then I'll look at the changes again.

**Comment by aidanfar0** [comment]
Whilst I have rebased this, the staging area now doesn't work for draft documents.
This is because it previously used 'null' as the record ID for drafts, but now that is not possible (due to better types). 
Each time you make a new record, you create a new ID, instead of looking for an existing draft,
So don't merge this yet!

**Comment by aidanfar0** [comment]
its fixed now

**Comment by aidanfar0** [comment]
its fixed now

**Pull request merged**
