### PR TITLE
Multiple drafts

### PR DESCRIPTION
**Pull request by aidanfar0**
This changes the staging area (renames to draft storage) and the Record form to enable multiple drafts
NOTE however that this doesn't let you access drafts once created, unless you save the link,
Hence this is WIP until we figure out the GUI to browse drafts

### CODE REVIEW

**Comment by aragilar** [comment]
Is there a way to list the available drafts, and hence generate the links? You could as a first pass loop over that list and have a page which just dumps out those, and we make it nice later.

**Comment by aidanfar0** [comment]
@KateSHENG List the drafts of a project - listStagedData(project_id, filter) - src/sync/draft-storage.ts
Listen for changes in drafts - listenDrafts(project_id, filter) - src/data_storage/listeners.ts
I presume the draft list will be displayed in src/gui/components/project/card.tsx
The draft list should use the URL: 
(If the draft .existing === null):
```
  ROUTES.PROJECT +
  ':project_id' +
  ROUTES.RECORD_CREATE +
  ':type_name' +
  ROUTES.RECORD_DRAFT + //
  ':draft_id'
```
Otherwise, if draft.existing !== null
```
  ROUTES.PROJECT +
  ':project_id' +
  ROUTES.RECORD_EXISTING +
  ':record_id' +
  ROUTES.REVISION +
  ':revision_id' +
  ROUTES.RECORD_DRAFT +
  ':draft_id'
```

**Comment by aidanfar0** [comment]
@aragilar this should be good to merge now
I fixed the extra commits from mult-form_components, theyre removed now (weren't needed)

**Pull request merged**
