### PR TITLE
New mui upgrade

### PR DESCRIPTION
**Pull request by aragilar**

### CODE REVIEW

**Comment by riniangreani** [comment]
Issues with this branch is documented here: https://faimsproject.atlassian.net/browse/FAIMS3-368

**Comment by aragilar** [comment]
@riniangreani Can you check the APK from https://github.com/FAIMS/FAIMS3/suites/5779261858/artifacts/192586309 (the latest build) and see if login works for you, it works on my phone.

**Comment by riniangreani** [comment]
@aragilar yes that one works

**Pull request merged**
