### PR TITLE
feat: survey list home page

### PR DESCRIPTION
**Pull request by luke-mcfarlane-rocketlab**
## JIRA Ticket

[BSS-129](https://jira.csiro.au/browse/BSS-129)

## Description

Update home page to be the survey list page. 

## Proposed Changes

- updated survey list to be on "/" route
- removed current component on "/" route
- updated all links to survey list to the "/" route

## How to Test

- log in to app
- home page should be survey list page
- try navigating away and back by clicking the logo/sidebar link
- log out of the app
- try navigating to http://localhost:3000/ and verify it redirects to the sign in page

## Checklist
 
- [x] I have confirmed all commits have been signed.
- [x] I have added JSDoc style comments to any new functions or classes.
- [x] Relevant documentation such as READMEs, guides, and class comments are updated.

### CODE REVIEW

**Comment by stevecassidy** [comment]
Should we redirect to the home page (survey list) after login? Currently it returns you to the login page and you need to click on "Workspace" to get there.

**Comment by luke-mcfarlane-rocketlab** [comment]
> Should we redirect to the home page (survey list) after login? Currently it returns you to the login page and you need to click on "Workspace" to get there.

Agree with this, will update and re-request.

**Comment by luke-mcfarlane-rocketlab** [comment]
@stevecassidy actioned

**Review by stevecassidy — APPROVED** [review]
All good.

**Pull request merged**
