### PR TITLE
Add possible fix for draft over flashing

### PR DESCRIPTION
**Pull request by aragilar**
There was a missing call to switch off flashing once the save was completed, add it in, and remove unused props which may confuse the issue.

Possible fix for FAIMS3-520.

### CODE REVIEW

**Comment by Denubis** [comment]
bors cancel

**Comment by Denubis** [comment]
@aragilar I was in the wrong PR when I hit +.

**Comment by lmannering** [comment]
@aragilar i've added the draft component to record-create, feel free to merge if you're happy with it

**Comment by lmannering** [comment]
I think this is now under-flashing! We might need to set a minimum timeout (1500ms?) to give the user a chance to read the text.

**Pull request merged**
