### PR TITLE
Update capacitor to v4

### PR DESCRIPTION
**Pull request by aragilar**
This is the changes generated by `npx cap migrate`. I don't see anything concerning here, but @Denubis can you have a quick look?

### CODE REVIEW

**Comment by aragilar** [comment]
Ok, something is wrong with the CI: on both the Mac that I did the upgrade on and my laptop, `npm ci` works fine, but here it errors...

**Comment by aragilar** [comment]
I've deleted and recreated the lock file (not that anything should have changed), let's see if this works.

**Comment by aragilar** [comment]
`add-filesystem-deps` and `add-app-download` should be merged once this has been merged.

**Comment by Denubis** [comment]
Testing protocol. I'm going to merge this, then I'm going to trigger the github-google play build. If that works, I'm going to trigger the fieldmark demo build. If that works, we can move on to `add-filesystem-deps` and `add-app-download` -- I just don't want to move too quickly, since I still haven't resolved testing.3's rebuild.

**Pull request merged**
